name: Build and Test

on: [push, pull_request]


jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - if: startswith(matrix.os, 'windows')
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Configure
        shell: bash
        run: cmake -G Ninja -B build -S .

      - name: Build
        shell: bash
        run: cmake --build build

      - name: Test
        shell: bash
        run: cd build && ctest -R '^TPack' --output-on-failure

      - name: Install
        shell: bash
        run: cmake --install build --prefix ~/tpack

      - name: Consume Installed
        shell: bash
        run: cd example && mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=~/tpack .. && cmake --build .
